logging:
    level:
        com:
            springboot:
                tutorial:
                    demo01:
                        controller: info
                        mapper: debug
#监控认证关闭
management:
    security:
        enabled: false
mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml
    type-aliases-package: com.springboot.demo01.entity
server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://192.168.188.135:3306/springbootdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    resources:
        chain:
            strategy:
                content:
#                md5方式管理静态资源（针对某个文件）不被浏览器缓存方案
                    enabled: true
                    paths: /**
                fixed:
#                统一资源版本号管理（所有静态资源文件）不被浏览器缓存
                    enabled: true
                    paths: /js/**,/v1.0.0/**
                    version: v1.0.1
    thymeleaf:
#    这个开发配置为false，避免改了模板还要重启服务器
        cache: false
#        这个可以不配置，检查模板位置
        check-template-location: true
        content-type: text/html
        encoding: UTF-8
        mode: HTML5
#        这个是配置模板路径的，默认就是templates，可不用配置
        prefix: classpath:/templates/
        suffix: .html
hello:
  msg: what's your name?
  show: false